name : Format Markdown 

permissions:
  contents: write

on: 
  push:
    paths: 
      - 'data_science_practice/1_git_&github/**.md'

jobs : 
  format:
    runs-on : ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Count Markdown files
      run: |
        dir="data_science_practice/1_git_&github"
        count=$(find "$dir" -name "*.md" | wc -l)
        echo "Found $count Markdown files."

    - name: Check Markdown structure
      run: |
        echo "Checking Markdown files for basic structure..."
        find . -name "*.md" -type f | while IFS= read -r file; do
          echo "Checking $file"
          if grep -q "^# " "$file"; then
            echo "$file has a main heading"
          else
            echo "$file missing main heading"
          fi
        done

    - name: Generate Table of contents
      run: |
        echo "Generating Table of Contents for Markdown files..."
        echo "## Repo Structure " > TOC.md
        echo "" >> TOC.md
        echo "### Markdown Files: " >> TOC.md
        find "data_science_practice/1_git_&github" -name "*.md" -type f | while IFS= read -r file; do
          echo "- $file" >> TOC.md
        done
        cat TOC.md
        mv TOC.md "data_science_practice/1_git_&github/TOC.md"

    - name: Commit TOC if changed
      run: |
        set -euo pipefail
        repo_dir="data_science_practice/1_git_&github"
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add "$repo_dir/TOC.md"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update TOC.md [ci skip]"
          branch=${GITHUB_REF#refs/heads/}
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:refs/heads/$branch
        fi
